services:
  genealogy.api:
    image: genealogy.api
    build:
      context: .
      dockerfile: Genealogy.API/Dockerfile

  database:
    image: neo4j:5.26.2
    container_name: genealogy.db
    ports:
      - "7474:7474"   # Neo4j Browser interface
      - "7687:7687"   # Bolt protocol for drivers
    environment:
      - NEO4J_AUTH=neo4j/p@ssw0rd
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data: